version: '3.8'
services:
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb
    ports:
      - "7000:7000" # YugabyteDB Admin UI
      - "9000:9000" # YugabyteDB YCQL API
      - "5433:5433" # YugabyteDB YSQL API (PostgreSQL compatible)
    command: bin/yugabyted start --daemon=false
    volumes:
      - yugabytedb_data:/var/lib/yugabyte # Persistent data storage

  springboot-app:
    build:
      context: . # Path to your Spring Boot project root
      dockerfile: Dockerfile # Name of your Spring Boot Dockerfile
    container_name: springboot-app
    ports:
      - "9098:9098" # Or your application's port
    environment:
      # Database connection properties for Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://yugabytedb:5433/yugabyte # Use service name 'yugabytedb'
      SPRING_DATASOURCE_USERNAME: yugabyte
      SPRING_DATASOURCE_PASSWORD: yugabyte
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Or create, validate, none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - yugabytedb # Ensures YugabyteDB starts before the Spring Boot app

volumes:
  yugabytedb_data: # Define a named volume for persistent data