package org.npci.bhim.BHIMSMSserviceAPI.responseDTO;

import jakarta.annotation.Nullable;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NonNull;

/**
 *A delivery report contains the status and state of each message sent through the Sinch India WhatsApp API.
 *
 * The default format of a delivery report is as mentioned below:
 *
 * Name	                        Description	                                                       JSON Type
 * del_status	The status of the message. It can be delivered, read, sent or failed.	            String
 * del_time	    ISO-8601 datetime of the status update.	                                            String
 * rqst_ack_id	The acknowledgment of the message created by meta.	                                String
 * messageId	Unique id of each message provided by enterprise or autogenerated by Sinch India.	String
 *
 * ---------------------------------------------------------------------------------------------------
 *
 * Success DLRs
 *
 * S.No	Description	Reason
 * 1	Sent	    Message sent to user but yet to be delivered.
 * 2	Delivered	Message delivered but yet to be read by customer. Message will reflect as delivered if customer has marked the read receipts as off.
 * 3	Read	    Delivered message is read by customer.
 *
 * Failure Codes
 *
 * Error        Description	       Error Code
 * MISSING MOBILE NUMBER AND WA ID	-6
 * OPTIN BLOCKED	                24
 * INVALID ENCRYPTED DATA	        26
 * REQUIRED PARAMETER IS MISSING	1008
 *  */
public record WADeliveryReport(String rqst_ack_id, String del_time, String moble_no, String messageId, String del_status, @Nullable String del_desc) {
}

